/// <reference path="../types/json2csv.d.ts" />
import PDFDocument from 'pdfkit';
import { Response } from 'express';

type PDFDoc = InstanceType<typeof PDFDocument>;

export type ExportFormat = 'json' | 'csv' | 'pdf';

export type ReportKind =
  | 'inventory'
  | 'inspection-status'
  | 'inspection-list'
  | 'expired'
  | 'maintenance'
  | 'compliance'
  | 'maintenance-frequency'
  | 'generic';

export interface ReportExportMeta {
  title: string;
  kind: ReportKind;
  data: unknown;
}

const BRAND = {
  company: 'TZW LTD',
  system: 'Fire Extinguisher Management System',
  primary: '#991B1B',
  primaryDark: '#7F1D1D',
  accent: '#C2410C',
  headerBg: '#1E293B',
  headerText: '#FFFFFF',
  muted: '#64748B',
  border: '#E2E8F0',
  rowAlt: '#F8FAFC',
};

// ─── Public API ─────────────────────────────────────────────────────────────

export function sendReport(res: Response, meta: ReportExportMeta, format: ExportFormat) {
  if (format === 'csv') {
    const csv = buildBusinessCsv(meta);
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${slug(meta.title)}-${dateSlug()}.csv"`);
    return res.send('\uFEFF' + csv);
  }

  if (format === 'pdf') {
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${slug(meta.title)}-${dateSlug()}.pdf"`);
    const doc = new PDFDocument({ margin: 48, size: 'A4', bufferPages: true });
    doc.pipe(res);
    buildBusinessPdf(doc, meta);
    doc.end();
    return;
  }

  return res.json({ success: true, data: meta.data });
}

export function parseFormat(q: unknown): ExportFormat {
  const f = String(q || 'json').toLowerCase();
  if (f === 'csv' || f === 'pdf') return f;
  return 'json';
}

export function groupByPeriod(items: { createdAt?: string; installationDate?: string }[], dateField: 'createdAt' | 'installationDate') {
  const now = new Date();
  const today = startOfDay(now);
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const yearStart = new Date(now.getFullYear(), 0, 1);

  let daily = 0, monthly = 0, yearly = 0;
  for (const item of items) {
    const raw = item[dateField];
    if (!raw) continue;
    const d = startOfDay(new Date(raw));
    if (d.getTime() === today.getTime()) daily++;
    if (d >= monthStart) monthly++;
    if (d >= yearStart) yearly++;
  }
  return { daily, monthly, yearly };
}

/** @deprecated use buildBusinessCsv paths */
export function toCsvRows(data: unknown): Record<string, unknown>[] {
  if (Array.isArray(data)) return data as Record<string, unknown>[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.items)) return obj.items as Record<string, unknown>[];
    return [obj];
  }
  return [{ value: data }];
}

// ─── CSV ────────────────────────────────────────────────────────────────────

function buildBusinessCsv(meta: ReportExportMeta): string {
  const lines: string[] = [];
  const generatedAt = extractGeneratedAt(meta.data);

  lines.push(...csvHeaderBlock(meta.title, generatedAt));

  switch (meta.kind) {
    case 'inventory':
      lines.push(...csvInventory(meta.data as InventoryData));
      break;
    case 'inspection-status':
      lines.push(...csvInspectionStatus(meta.data as InspectionStatusData));
      break;
    case 'inspection-list':
      lines.push(...csvInspectionList(meta.data));
      break;
    case 'expired':
      lines.push(...csvExtinguisherList('Expired Extinguishers', meta.data));
      break;
    case 'maintenance':
      lines.push(...csvMaintenance(meta.data as MaintenanceData));
      break;
    case 'compliance':
      lines.push(...csvCompliance(meta.data as ComplianceData));
      break;
    case 'maintenance-frequency':
      lines.push(...csvMaintenanceFrequency(meta.data as MaintenanceFrequencyData));
      break;
    default:
      lines.push(...csvGeneric(meta.data));
      break;
  }

  lines.push('');
  lines.push(...csvTableBlock('Document Footer', [
    { key: 'note', label: 'Note' },
  ], [
    { note: `Report generated by ${BRAND.company} ${BRAND.system}` },
    { note: 'Confidential — For internal business use only' },
  ]));

  return lines.join('\r\n');
}

/** Exposed for unit tests */
export function buildBusinessCsvPreview(meta: ReportExportMeta): string {
  return '\uFEFF' + buildBusinessCsv(meta);
}

function csvHeaderBlock(title: string, generatedAt: string | null): string[] {
  const when = generatedAt ? formatDisplayDate(generatedAt) : formatDisplayDate(new Date().toISOString());
  return csvTableBlock('Report Information', [
    { key: 'field', label: 'Field' },
    { key: 'value', label: 'Value' },
  ], [
    { field: 'Organization', value: `${BRAND.company} — ${BRAND.system}` },
    { field: 'Report Title', value: title },
    { field: 'Generated', value: when },
  ]);
}

function escapeCsvCell(value: unknown): string {
  const s = value == null || value === '' ? '—' : String(value);
  if (/[",\r\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function csvTableBlock(
  sectionTitle: string,
  columns: { key: string; label: string }[],
  rows: Record<string, string>[],
): string[] {
  const lines: string[] = [];
  const width = Math.max(columns.length, 1);

  lines.push([
    escapeCsvCell(sectionTitle),
    ...Array.from({ length: width - 1 }, () => ''),
  ].join(','));

  lines.push(columns.map((c) => escapeCsvCell(c.label)).join(','));

  if (rows.length === 0) {
    lines.push(columns.map(() => escapeCsvCell('—')).join(','));
  } else {
    for (const row of rows) {
      lines.push(columns.map((c) => escapeCsvCell(row[c.key] ?? '—')).join(','));
    }
  }

  lines.push('');
  return lines;
}

function csvKeyValueSection(title: string, pairs: { label: string; value: string | number }[]): string[] {
  return csvTableBlock(
    title,
    [{ key: 'metric', label: 'Metric' }, { key: 'value', label: 'Value' }],
    pairs.map((p) => ({ metric: p.label, value: String(p.value) })),
  );
}

function csvSection(title: string, rows: Record<string, string>[], columns: { key: string; label: string }[]): string[] {
  return csvTableBlock(title, columns, rows);
}

const INSPECTION_COLUMNS = [
  { key: 'serialNumber', label: 'Serial Number' },
  { key: 'location', label: 'Location' },
  { key: 'scheduledDate', label: 'Scheduled Date' },
  { key: 'scheduledTime', label: 'Scheduled Time' },
  { key: 'status', label: 'Status' },
  { key: 'inspectorEmail', label: 'Assigned Inspector' },
];

const EXTINGUISHER_COLUMNS = [
  { key: 'serialNumber', label: 'Serial Number' },
  { key: 'location', label: 'Location' },
  { key: 'type', label: 'Type' },
  { key: 'size', label: 'Size' },
  { key: 'status', label: 'Status' },
  { key: 'installationDate', label: 'Installation Date' },
  { key: 'expiryDate', label: 'Expiry Date' },
];

const MAINTENANCE_COLUMNS = [
  { key: 'serialNumber', label: 'Extinguisher Serial' },
  { key: 'location', label: 'Location' },
  { key: 'actionTaken', label: 'Action Taken' },
  { key: 'maintenanceDate', label: 'Maintenance Date' },
  { key: 'inspectorEmail', label: 'Inspector' },
  { key: 'issuesIdentified', label: 'Issues Identified' },
  { key: 'recommendations', label: 'Recommendations' },
  { key: 'notes', label: 'Notes' },
];

interface InventoryData {
  total?: number;
  daily?: number;
  monthly?: number;
  yearly?: number;
  byStatus?: Record<string, number>;
  byType?: Record<string, number>;
}

function csvInventory(data: InventoryData): string[] {
  const lines = csvKeyValueSection('Executive Summary — Stock Levels', [
    { label: 'Total Extinguishers in Stock', value: data.total ?? 0 },
    { label: 'Registered Today', value: data.daily ?? 0 },
    { label: 'Registered This Month', value: data.monthly ?? 0 },
    { label: 'Registered This Year', value: data.yearly ?? 0 },
  ]);

  if (data.byStatus && Object.keys(data.byStatus).length > 0) {
    lines.push(...csvSection(
      'Breakdown by Status',
      Object.entries(data.byStatus).map(([status, count]) => ({
        status: humanize(status),
        count: String(count),
      })),
      [{ key: 'status', label: 'Status' }, { key: 'count', label: 'Count' }],
    ));
  }

  if (data.byType && Object.keys(data.byType).length > 0) {
    lines.push(...csvSection(
      'Breakdown by Type',
      Object.entries(data.byType).map(([type, count]) => ({
        type: humanize(type),
        count: String(count),
      })),
      [{ key: 'type', label: 'Extinguisher Type' }, { key: 'count', label: 'Count' }],
    ));
  }

  return lines;
}

interface InspectionStatusData {
  summary?: Record<string, number>;
  items?: Record<string, unknown>[];
}

function csvInspectionStatus(data: InspectionStatusData): string[] {
  const s = data.summary ?? {};
  const lines = csvKeyValueSection('Executive Summary — Inspection Status', [
    { label: 'Total Inspections', value: s.total ?? 0 },
    { label: 'Pending', value: s.PENDING ?? 0 },
    { label: 'Completed', value: s.COMPLETED ?? 0 },
    { label: 'Overdue', value: s.OVERDUE ?? 0 },
    { label: 'Cancelled', value: s.CANCELLED ?? 0 },
  ]);

  const rows = (data.items ?? []).map(flattenInspection);
  lines.push(...csvSection('Inspection Detail', rows, INSPECTION_COLUMNS));

  return lines;
}

function csvInspectionList(data: unknown): string[] {
  const items = Array.isArray(data)
    ? data
    : data && typeof data === 'object' && Array.isArray((data as { items?: unknown[] }).items)
      ? (data as { items: Record<string, unknown>[] }).items
      : [];

  const rows = items.map(flattenInspection);
  const lines = csvKeyValueSection('Executive Summary', [
    { label: 'Total Inspections', value: rows.length },
  ]);
  lines.push(...csvSection('Inspection Detail', rows, INSPECTION_COLUMNS));
  return lines;
}

function csvExtinguisherList(sectionTitle: string, data: unknown): string[] {
  const items = Array.isArray(data) ? data : [];
  const rows = items.map(flattenExtinguisher);
  const lines = csvKeyValueSection('Executive Summary', [
    { label: 'Total Records', value: rows.length },
  ]);
  lines.push(...csvSection(sectionTitle, rows, EXTINGUISHER_COLUMNS));
  return lines;
}

interface MaintenanceData {
  total?: number;
  items?: Record<string, unknown>[];
}

function csvMaintenance(data: MaintenanceData): string[] {
  const lines = csvKeyValueSection('Executive Summary', [
    { label: 'Total Maintenance Records', value: data.total ?? data.items?.length ?? 0 },
  ]);

  const rows = (data.items ?? []).map(flattenMaintenance);
  lines.push(...csvSection('Maintenance History Detail', rows, MAINTENANCE_COLUMNS));

  return lines;
}

interface ComplianceData {
  total?: number;
  compliant?: number;
  expired?: number;
  complianceRate?: number;
  status?: string;
}

function csvCompliance(data: ComplianceData): string[] {
  return csvKeyValueSection('Compliance Summary', [
    { label: 'Total Extinguishers', value: data.total ?? 0 },
    { label: 'Compliant (Active)', value: data.compliant ?? 0 },
    { label: 'Expired', value: data.expired ?? 0 },
    { label: 'Compliance Rate (%)', value: data.complianceRate ?? 0 },
    { label: 'Status', value: humanize(str(data.status)) },
  ]);
}

interface MaintenanceFrequencyData {
  total?: number;
  byMonth?: Record<string, number>;
}

function csvMaintenanceFrequency(data: MaintenanceFrequencyData): string[] {
  const lines = csvKeyValueSection('Executive Summary', [
    { label: 'Total Maintenance Records', value: data.total ?? 0 },
  ]);

  const byMonth = data.byMonth ?? {};
  if (Object.keys(byMonth).length > 0) {
    lines.push(...csvSection(
      'Maintenance by Month',
      Object.entries(byMonth)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([month, count]) => ({ month, count: String(count) })),
      [{ key: 'month', label: 'Month' }, { key: 'count', label: 'Maintenance Count' }],
    ));
  }

  return lines;
}

function csvGeneric(data: unknown): string[] {
  const rawRows = toCsvRows(data);
  if (rawRows.length === 0) {
    return csvTableBlock('Report Data', [{ key: 'message', label: 'Message' }], [
      { message: 'No records found' },
    ]);
  }

  const first = rawRows[0] as Record<string, unknown>;
  const columns = Object.keys(first).map((key) => ({
    key,
    label: humanize(key),
  }));

  const rows = rawRows.map((r) =>
    Object.fromEntries(
      Object.entries(r as Record<string, unknown>).map(([k, v]) => [k, str(v)]),
    ),
  );

  return csvTableBlock('Report Data', columns, rows);
}

// ─── PDF ────────────────────────────────────────────────────────────────────

function buildBusinessPdf(doc: PDFDoc, meta: ReportExportMeta) {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const generatedAt = extractGeneratedAt(meta.data);

  drawPdfLetterhead(doc, meta.title, generatedAt, pageWidth);

  switch (meta.kind) {
    case 'inventory':
      drawInventoryPdf(doc, meta.data as InventoryData, pageWidth);
      break;
    case 'inspection-status':
      drawInspectionStatusPdf(doc, meta.data as InspectionStatusData, pageWidth);
      break;
    case 'expired':
      drawExtinguisherTablePdf(doc, 'Expired Extinguisher Register', meta.data, pageWidth);
      break;
    case 'maintenance':
      drawMaintenancePdf(doc, meta.data as MaintenanceData, pageWidth);
      break;
    default:
      drawGenericPdf(doc, meta.data, pageWidth);
      break;
  }

  addPdfFooters(doc);
}

function drawPdfLetterhead(doc: PDFDoc, title: string, generatedAt: string | null, pageWidth: number) {
  const left = doc.page.margins.left;

  doc.save();
  doc.rect(left, 40, pageWidth, 4).fill(BRAND.primary);
  doc.restore();

  doc.font('Helvetica-Bold').fontSize(20).fillColor(BRAND.primaryDark)
    .text(BRAND.company, left, 52, { width: pageWidth, align: 'left' });

  doc.font('Helvetica').fontSize(10).fillColor(BRAND.muted)
    .text(BRAND.system, left, 76);

  doc.font('Helvetica').fontSize(8).fillColor(BRAND.muted)
    .text('CONFIDENTIAL', left, 52, { width: pageWidth, align: 'right' });

  doc.moveTo(left, 96).lineTo(left + pageWidth, 96).strokeColor(BRAND.border).lineWidth(1).stroke();

  doc.font('Helvetica-Bold').fontSize(16).fillColor('#0F172A')
    .text(title, left, 108, { width: pageWidth });

  const when = generatedAt ? formatDisplayDate(generatedAt) : formatDisplayDate(new Date().toISOString());
  doc.font('Helvetica').fontSize(9).fillColor(BRAND.muted)
    .text(`Report generated: ${when}`, left, 130);

  doc.y = 152;
}

function drawKpiRow(doc: PDFDoc, metrics: { label: string; value: string | number }[], pageWidth: number) {
  const left = doc.page.margins.left;
  const perRow = metrics.length > 4 ? 3 : Math.min(metrics.length, 4);
  const gap = 8;
  const boxH = 52;

  for (let offset = 0; offset < metrics.length; offset += perRow) {
    const chunk = metrics.slice(offset, offset + perRow);
    const boxW = (pageWidth - gap * (chunk.length - 1)) / chunk.length;
    const startY = doc.y;

    chunk.forEach((m, i) => {
      const x = left + i * (boxW + gap);
      doc.save();
      doc.roundedRect(x, startY, boxW, boxH, 4).fillAndStroke(BRAND.rowAlt, BRAND.border);
      doc.restore();

      doc.font('Helvetica').fontSize(7).fillColor(BRAND.muted)
        .text(m.label.toUpperCase(), x + 10, startY + 10, { width: boxW - 20, align: 'left' });

      doc.font('Helvetica-Bold').fontSize(16).fillColor(BRAND.primaryDark)
        .text(String(m.value), x + 10, startY + 26, { width: boxW - 20, align: 'left' });
    });

    doc.y = startY + boxH + 12;
  }

  doc.y += 4;
}

function drawSectionTitle(doc: PDFDoc, title: string, pageWidth: number) {
  ensureSpace(doc, 40);
  const left = doc.page.margins.left;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(BRAND.primaryDark)
    .text(title, left, doc.y, { width: pageWidth });
  doc.moveDown(0.4);
}

interface PdfColumn {
  header: string;
  width: number;
  get: (row: Record<string, string>) => string;
}

function drawDataTable(
  doc: PDFDoc,
  columns: PdfColumn[],
  rows: Record<string, string>[],
  pageWidth: number,
) {
  if (rows.length === 0) {
    doc.font('Helvetica-Oblique').fontSize(9).fillColor(BRAND.muted).text('No records found.');
    doc.moveDown(0.8);
    return;
  }

  const left = doc.page.margins.left;
  const rowH = 22;
  const headerH = 24;

  const drawHeader = (y: number) => {
    doc.save();
    doc.rect(left, y, pageWidth, headerH).fill(BRAND.headerBg);
    doc.restore();

    let x = left;
    doc.font('Helvetica-Bold').fontSize(8).fillColor(BRAND.headerText);
    for (const col of columns) {
      doc.text(col.header, x + 6, y + 7, { width: col.width - 12, lineBreak: false });
      x += col.width;
    }
  };

  const drawRow = (row: Record<string, string>, y: number, alt: boolean) => {
    if (alt) {
      doc.save();
      doc.rect(left, y, pageWidth, rowH).fill(BRAND.rowAlt);
      doc.restore();
    }

    let x = left;
    doc.font('Helvetica').fontSize(8).fillColor('#334155');
    for (const col of columns) {
      const val = truncate(col.get(row), Math.floor(col.width / 5));
      doc.text(val, x + 6, y + 6, { width: col.width - 12, lineBreak: false });
      x += col.width;
    }
  };

  let y = doc.y;
  drawHeader(y);
  y += headerH;

  rows.forEach((row, idx) => {
    if (y + rowH > doc.page.height - doc.page.margins.bottom - 40) {
      doc.addPage();
      drawPdfLetterheadContinued(doc, pageWidth);
      y = doc.y;
      drawHeader(y);
      y += headerH;
    }
    drawRow(row, y, idx % 2 === 1);
    y += rowH;
  });

  doc.y = y + 12;
}

function drawPdfLetterheadContinued(doc: PDFDoc, pageWidth: number) {
  const left = doc.page.margins.left;
  doc.font('Helvetica-Bold').fontSize(10).fillColor(BRAND.muted)
    .text(`${BRAND.company} — ${BRAND.system} (continued)`, left, 48);
  doc.moveTo(left, 64).lineTo(left + pageWidth, 64).strokeColor(BRAND.border).stroke();
  doc.y = 76;
}

function drawInventoryPdf(doc: PDFDoc, data: InventoryData, pageWidth: number) {
  drawKpiRow(doc, [
    { label: 'Total in Stock', value: data.total ?? 0 },
    { label: 'Added Today', value: data.daily ?? 0 },
    { label: 'Added This Month', value: data.monthly ?? 0 },
    { label: 'Added This Year', value: data.yearly ?? 0 },
  ], pageWidth);

  if (data.byStatus && Object.keys(data.byStatus).length > 0) {
    drawSectionTitle(doc, 'Inventory by Status', pageWidth);
    drawDataTable(doc, [
      { header: 'Status', width: pageWidth * 0.6, get: (r) => r.status },
      { header: 'Count', width: pageWidth * 0.4, get: (r) => r.count },
    ], Object.entries(data.byStatus).map(([status, count]) => ({
      status: humanize(status),
      count: String(count),
    })), pageWidth);
  }

  if (data.byType && Object.keys(data.byType).length > 0) {
    drawSectionTitle(doc, 'Inventory by Type', pageWidth);
    drawDataTable(doc, [
      { header: 'Type', width: pageWidth * 0.6, get: (r) => r.type },
      { header: 'Count', width: pageWidth * 0.4, get: (r) => r.count },
    ], Object.entries(data.byType).map(([type, count]) => ({
      type: humanize(type),
      count: String(count),
    })), pageWidth);
  }
}

function drawInspectionStatusPdf(doc: PDFDoc, data: InspectionStatusData, pageWidth: number) {
  const s = data.summary ?? {};
  drawKpiRow(doc, [
    { label: 'Total', value: s.total ?? 0 },
    { label: 'Pending', value: s.PENDING ?? 0 },
    { label: 'Completed', value: s.COMPLETED ?? 0 },
    { label: 'Overdue', value: s.OVERDUE ?? 0 },
    { label: 'Cancelled', value: s.CANCELLED ?? 0 },
  ], pageWidth);

  drawSectionTitle(doc, 'Inspection Register', pageWidth);
  const rows = (data.items ?? []).map(flattenInspection);
  drawDataTable(doc, [
    { header: 'Serial', width: pageWidth * 0.14, get: (r) => r.serialNumber },
    { header: 'Location', width: pageWidth * 0.18, get: (r) => r.location },
    { header: 'Date', width: pageWidth * 0.12, get: (r) => r.scheduledDate },
    { header: 'Time', width: pageWidth * 0.08, get: (r) => r.scheduledTime },
    { header: 'Status', width: pageWidth * 0.12, get: (r) => r.status },
    { header: 'Inspector', width: pageWidth * 0.36, get: (r) => r.inspectorEmail },
  ], rows, pageWidth);
}

function drawExtinguisherTablePdf(doc: PDFDoc, sectionTitle: string, data: unknown, pageWidth: number) {
  const items = Array.isArray(data) ? data : [];
  drawKpiRow(doc, [{ label: 'Total Expired Units', value: items.length }], pageWidth);
  drawSectionTitle(doc, sectionTitle, pageWidth);
  const rows = items.map(flattenExtinguisher);
  drawDataTable(doc, [
    { header: 'Serial', width: pageWidth * 0.14, get: (r) => r.serialNumber },
    { header: 'Location', width: pageWidth * 0.2, get: (r) => r.location },
    { header: 'Type', width: pageWidth * 0.14, get: (r) => r.type },
    { header: 'Size', width: pageWidth * 0.1, get: (r) => r.size },
    { header: 'Status', width: pageWidth * 0.14, get: (r) => r.status },
    { header: 'Expiry', width: pageWidth * 0.14, get: (r) => r.expiryDate },
  ], rows, pageWidth);
}

function drawMaintenancePdf(doc: PDFDoc, data: MaintenanceData, pageWidth: number) {
  drawKpiRow(doc, [
    { label: 'Total Records', value: data.total ?? data.items?.length ?? 0 },
  ], pageWidth);

  drawSectionTitle(doc, 'Maintenance History', pageWidth);
  const rows = (data.items ?? []).map(flattenMaintenance);
  drawDataTable(doc, [
    { header: 'Serial', width: pageWidth * 0.12, get: (r) => r.serialNumber },
    { header: 'Action', width: pageWidth * 0.16, get: (r) => r.actionTaken },
    { header: 'Date', width: pageWidth * 0.1, get: (r) => r.maintenanceDate },
    { header: 'Issues', width: pageWidth * 0.22, get: (r) => r.issuesIdentified },
    { header: 'Recommendations', width: pageWidth * 0.22, get: (r) => r.recommendations },
    { header: 'Notes', width: pageWidth * 0.18, get: (r) => r.notes },
  ], rows, pageWidth);
}

function drawGenericPdf(doc: PDFDoc, data: unknown, pageWidth: number) {
  drawSectionTitle(doc, 'Report Data', pageWidth);
  doc.font('Helvetica').fontSize(9).fillColor('#334155')
    .text(JSON.stringify(data, null, 2), doc.page.margins.left, doc.y, { width: pageWidth });
}

function addPdfFooters(doc: PDFDoc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const left = doc.page.margins.left;
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const bottom = doc.page.height - doc.page.margins.bottom + 10;

    doc.moveTo(left, bottom - 14).lineTo(left + pageWidth, bottom - 14).strokeColor(BRAND.border).stroke();

    doc.font('Helvetica').fontSize(7).fillColor(BRAND.muted)
      .text(
        `© ${new Date().getFullYear()} ${BRAND.company} — ${BRAND.system}. Confidential.`,
        left,
        bottom - 10,
        { width: pageWidth * 0.7, align: 'left', lineBreak: false },
      );

    doc.font('Helvetica').fontSize(7).fillColor(BRAND.muted)
      .text(`Page ${i - range.start + 1} of ${range.count}`, left, bottom - 10, {
        width: pageWidth,
        align: 'right',
        lineBreak: false,
      });
  }
}

// ─── Row flatteners ─────────────────────────────────────────────────────────

function flattenExtinguisher(row: Record<string, unknown>): Record<string, string> {
  return {
    serialNumber: str(row.serialNumber),
    location: str(row.location),
    type: humanize(str(row.type)),
    size: humanizeSize(str(row.size)),
    status: humanize(str(row.status)),
    installationDate: formatShortDate(row.installationDate),
    expiryDate: formatShortDate(row.expiryDate),
  };
}

function flattenInspection(row: Record<string, unknown>): Record<string, string> {
  const ext = row.extinguisher as Record<string, unknown> | undefined;
  return {
    serialNumber: str(ext?.serialNumber),
    location: str(ext?.location),
    scheduledDate: formatShortDate(row.scheduledDate),
    scheduledTime: str(row.scheduledTime),
    status: humanize(str(row.status)),
    inspectorEmail: str(row.assignedInspectorEmail),
  };
}

function flattenMaintenance(row: Record<string, unknown>): Record<string, string> {
  const ext = row.extinguisher as Record<string, unknown> | undefined;
  return {
    serialNumber: str(ext?.serialNumber),
    location: str(ext?.location),
    actionTaken: str(row.actionTaken),
    maintenanceDate: formatShortDate(row.maintenanceDate),
    inspectorEmail: str(row.inspectorEmail),
    issuesIdentified: str(row.issuesIdentified) || '—',
    recommendations: str(row.recommendations) || '—',
    notes: str(row.notes) || '—',
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function slug(s: string) {
  return s.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

function dateSlug() {
  return new Date().toISOString().slice(0, 10);
}

function str(v: unknown): string {
  if (v == null || v === '') return '—';
  return String(v);
}

function humanize(s: string): string {
  if (!s || s === '—') return '—';
  return s.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function humanizeSize(s: string): string {
  if (!s || s === '—') return '—';
  return s.replace('LB_', '').replace(/_/g, ' ') + ' lb';
}

function formatShortDate(v: unknown): string {
  if (!v) return '—';
  try {
    return new Date(String(v)).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
  } catch {
    return String(v);
  }
}

function formatDisplayDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString('en-GB', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    });
  } catch {
    return iso;
  }
}

function extractGeneratedAt(data: unknown): string | null {
  if (data && typeof data === 'object' && !Array.isArray(data) && 'generatedAt' in data) {
    return String((data as { generatedAt: string }).generatedAt);
  }
  return null;
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1) + '…';
}

function ensureSpace(doc: PDFDoc, needed: number) {
  if (doc.y + needed > doc.page.height - doc.page.margins.bottom - 40) {
    doc.addPage();
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    drawPdfLetterheadContinued(doc, pageWidth);
  }
}

function startOfDay(d: Date) {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  return x;
}
